#!/bin/sh

# PROVIDE: jails_controller
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name="jails_controller"
rcvar="${name}_enable"

load_rc_config $name
: ${jails_controller_enable:=no}
: ${jails_controller_config:=/usr/local/etc/jails-controller/config.toml}

command="/usr/sbin/daemon"
pidfile="/var/run/${name}.pid"
command_args="-S -P ${pidfile} /usr/local/bin/jails-controller -config ${jails_controller_config}"

run_rc_command "$1"
